import bcrypt from 'bcryptjs';
const data = {
    users: [
        {
            name: 'Vaishnavi',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'Sakshi',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Womens Beautiful Silk Saree',
            category: 'sarees',
            image: '/images/p7.jpg',
            price: 239,
            countInStock: 9,
            brand: 'Banarasi Silk',
            rating: 3.9,
            numReviews: 26,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Chitrarekha Voguish Sarees',
            category: 'sarees',
            image: '/images/p8.jpg',
            price: 1039,
            countInStock: 8,
            brand: 'Dupion Silk',
            rating: 4.2,
            numReviews: 29,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Litchi Silk',
            category: 'sarees',
            image: '/images/p9.jpg',
            price: 590,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 4.7,
            tag: 'festival',
            numReviews: 9,
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Jacquard Work Saree With Blouse',
            category: 'sarees',
            image: '/images/p10.jpg',
            price: 550,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 3.7,
            numReviews: 9,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Latest Rasal Net Saree',
            category: 'sarees',
            image: '/images/p11.jpg',
            price: 380,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 5,
            numReviews: 25,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Sankhochur Jamdani saree',
            category: 'sarees',
            image: '/images/p12.jpg',
            price: 1041,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 4.2,
            numReviews: 10,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Litchi Silk',
            category: 'sarees',
            image: '/images/p13.jpg',
            price: 590,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 4.7,
            numReviews: 9,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Ladies Designer Digital Printed Linen Saree',
            category: 'sarees',
            image: '/images/p14.jpg',
            price: 450,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 4.7,
            numReviews: 119,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk, Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Litchi Silk',
            category: 'sarees',
            image: '/images/p15.jpg',
            price: 590,
            countInStock: 10,
            brand: 'Dupion Silk',
            rating: 4.7,
            numReviews: 9,
            tag: 'festival',
            description: 'Saree Fabric : Banarasi Silk,Blouse : Running Blouse,  Blouse Fabric : Banarasi Silk'
        },
        {
            name: 'Elegant Alloy & Pearl Jewellery Sets',
            category: 'jewellary',
            image: '/images/p16.jpg',
            price: 401,
            countInStock: 10,
            brand: 'Gold Plated',
            rating: 4.4,
            numReviews: 92,
            tag: 'festival',
            description: "Base Metal : Alloy, Plating : Gold Plated, Stone Type : Artificial Stones"
        },
        {
            name: 'Brass Gold Plated Jewellery Necklace',
            category: 'jewellary',
            image: '/images/p14.jpg',
            price: 84,
            countInStock: 10,
            brand: 'Gold Plated',
            rating: 4,
            numReviews: 9,
            tag: 'festival',
            description: "Base Metal : Alloy, Plating : Gold Plated, Stone Type : Artificial Stones"
        },
        {
            name: 'Twinkling Unique Jewellery Sets',
            category: 'jewellary',
            image: '/images/p17.jpg',
            price: 764,
            countInStock: 30,
            brand: 'Gold Plated',
            rating: 4.7,
            numReviews: 9,
            tag: 'festival',
            description: "Base Metal : Alloy, Plating : Gold Plated, Stone Type : Artificial Stones"
        },
        {
            name: 'Traditional Oxidized Silver',
            category: 'jewellary',
            image: '/images/p18.jpg',
            price: 84,
            countInStock: 10,
            brand: 'No Plated',
            rating: 3.7,
            numReviews: 9,
            tag: 'festival',
            description: "Base Metal : Alloy, Plating : No Plated, Stone Type : Artificial Stones"
        },
        {
            name: 'Fancy Earrings & Studs',
            category: 'jewellary',
            image: '/images/p19.jpg',
            price: 184,
            countInStock: 10,
            brand: 'Gold Plated',
            rating: 3,
            numReviews: 9,
            tag: 'festival',
            description: "Base Metal : Alloy, Plating : Gold Plated, Stone Type : Artificial Stones"
        },
        {
            name: 'Earrings',
            category: 'jewellary',
            image: '/images/p20.jpg',
            price: 114,
            countInStock: 10,
            brand: 'Gold Plated',
            rating: 4.9,
            numReviews: 35,
            tag: 'festival',
            description: "Base Metal : Alloy, Plating : Gold Plated, Stone Type : Artificial Stones"
        },
        {
            name: 'CREAM BAJRA Trendy Bangles',
            category: 'jewellary',
            image: '/images/p21.jpg',
            price: 262,
            countInStock: 20,
            brand: 'Gold Plated',
            rating: 4.9,
            numReviews: 35,
            tag: 'festival',
            description: "Base Metal : Meta, Plating : Gold Plated, Stone Type : Crystals"
        },
        {
            name: 'CREAM BAJRA Trendy Bangles',
            category: 'jewellary',
            image: '/images/p22.jpg',
            price: 262,
            countInStock: 20,
            brand: 'Gold Plated',
            rating: 4.9,
            numReviews: 35,
            tag: 'festival',
            description: "Base Metal : Meta, Plating : Gold Plated, Stone Type : Crystals"
        },
        {
            name: 'Kemp stone 6pc Bangles',
            category: 'jewellary',
            image: '/images/p23.jpg',
            price: 262,
            countInStock: 20,
            brand: 'Gold Plated',
            rating: 3.9,
            numReviews: 35,
            tag: 'festival',
            description: "Base Metal : Meta, Plating : Gold Plated, Stone Type : Crystals"
        },
        {
            name: 'Mattefinish Jewellery Set',
            category: 'jewellary',
            image: '/images/p24.jpg',
            price: 250,
            countInStock: 40,
            brand: 'Gold Plated',
            rating: 3.3,
            numReviews: 35,
            tag: 'festival',
            description: "Base Metal : Meta, Plating : Gold Plated, Stone Type : Crystals"
        },
        {
            name: 'MANS BLACK SHIRT',
            category: 'Shirts',
            image: '/images/p25.jpg',
            price: 210,
            countInStock: 10,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Fashionable Men Kurtas',
            category: 'Shirts',
            image: '/images/p26.jpg',
            price: 275,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            tag: 'festival',
            description: 'High quality product'
        },
        {
            name: 'Fancy Men Ethnic Jackets',
            category: 'Shirts',
            image: '/images/p27.jpg',
            price: 680,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.7,
            numReviews: 110,
            tag: 'festival',
            description: 'High quality product'
        },
        {
            name: 'Larwa Mens KurtaFirozi',
            category: 'Shirts',
            image: '/images/p28.jpg',
            price: 567,
            countInStock: 10,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 60,
            tag: '',
            description: 'Fabric : Jacquard'
        },
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4,
            numReviews: 10,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Nike Slim Pants',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 15,
            tag: '',
            description: 'High quality product'
        },
        {
            name: 'Kcoy Mens Light Blue Jeans',
            category: 'Pants',
            image: '/images/p29.jpg',
            price: 139,
            countInStock: 12,
            brand: 'Adidas',
            rating: 2.9,
            numReviews: 15,
            tag: '',
            description: 'Kcoy Mens Jeans Slim tapered fit in last one Ultra Light Weight spandex denim, ROW with tailor-inspired '
        },
        {
            name: 'Casual Glamarous Men Jeans',
            category: 'Pants',
            image: '/images/p30.jpg',
            price: 329,
            countInStock: 12,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 15,
            tag: '',
            description: 'High quality product'
        }   
    ]
};

export default data;