products = [
    {
        name: 'Clean & Clear Face Wash',
        category: 'women beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/kjkbv680-0/face-wash/l/r/7/450-face-wash-clean-clear-original-imafz3hz4fgwhfnf.jpeg?q=70',
        price: 360,
        countInStock: 20,
        brand: 'Clean & Clear',
        rating: 4.6,
        tag: 'summer',
        numReviews: 9,
        description: 'Model Name -Face Wash, Quantity-450 ml,Ideal For-Men & Women,Face Wash Type-Gel'
    },
    {
        name: 'PONDS Moisturising Body Lotion',
        category: 'women beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/ktuewsw0/moisturizer-cream/i/l/1/triple-vitamin-moisturising-body-lotion-lotion-pond-s-original-imag73h4rtaumppn.jpeg?q=70',
        price: 254,
        countInStock: 15,
        brand: 'Ponds',
        rating: 4.3,
        tag: 'winter',
        numReviews: 9,
        description: 'This winter, choose silky smooth and soft skin with Ponds Moisturizing Body Lotion.'
    },
    {
        name: 'Vaseline Intensive Care Deep',
        category: 'beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/kh3qkcw0/moisturizer-cream/y/f/q/200-intensive-care-deep-restore-body-lotion-vaseline-lotion-original-imafx6zgnjetsnjx.jpeg?q=70',
        price: 160,
        countInStock: 10,
        brand: 'Vaseline',
        rating: 4.3,
        tag: 'winter',
        numReviews: 9,
        description: 'Pamper your dry skin with the Vaseline Intensive Care body lotion to get healthier and healed skin.'
    },
    {
        name: ' Coconut Hair Oil',
        category: 'beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/kdrpksw0/hair-oil/5/q/h/400-gold-coconut-hair-oil-parachute-advansed-original-imafuhh9qdgwrppm.jpeg?q=70',
        price: 160,
        countInStock: 20,
        brand: 'Parachute Advansed',
        rating: 3.6,
        tag: 'winter',
        numReviews: 9,
        description: ' Parachute Advansed Gold strengthens this relationship through deep nourishment with the goodness of Pure Coconut Oil, and Vitamin E so that you get long.'
    },
    {
        name: 'MY TYA Fashion Makeup Kit',
        category: 'women beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/kh9gbrk0/combo-kit/8/s/x/fashion-makeup-kit-me-now-blendor-puffs-makeup-brushes-yanqina-original-imafxbdeyuwkhgdv.jpeg?q=70',
        price: 335,
        countInStock: 15,
        brand: 'Makeup Kits',
        rating: 4.6,
        tag: 'festival',
        numReviews: 9,
        description: '1 Makeup Kit, 5 Piece Brush Set, 1 Set of Makeup Sponges, 1 Eyeliner Black'
    },
    {
        name: 'BLUE HEAVEN Wedding Combo',
        category: 'women beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/knhsgi80/makeup-kit/k/l/z/wedding-combo-kit-blue-heaven-original-imag25y2hgwzstan.jpeg?q=70',
        price: 511,
        countInStock: 15,
        brand: 'BLUE HEAVEN',
        rating: 4.6,
        tag: 'festival',
        numReviews: 9,
        description: '1 Kajal || 1 Mascara || 1 Eye Liner || 1 Rose Water || 1 Foundation || 1 Compact || 2 Nail Paints || 1 Lipstick || 1 Lip Balm || 1 Sindoor'
    },
    {
        name: 'Lakmé Liquid Foundation',
        category: 'women beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/krz97rk0/foundation/o/h/3/perfecting-liquid-lakme-original-imag5nkjhsr6vv8h.jpeg?q=70',
        price: 115,
        countInStock: 15,
        brand: 'Lakme',
        rating: 4,
        tag: 'festival',
        numReviews: 19,
        description: 'This foundation with a liquid base hides spots, blemishes and dark circles to make your skin look fresh and even'
    },
    {
        name: 'Yardley London Deo Tripack ',
        category: 'beauty',
        image: 'https://rukminim1.flixcart.com/image/416/416/k0sgl8w0/deodorant/v/n/k/450-london-deo-tripack-english-body-spray-yardley-women-original-imafjz74pgx4hghf.jpeg?q=70',
        price: 398,
        countInStock: 15,
        brand: 'Yardley London',
        rating: 3.9,
        tag: '',
        numReviews: 9,
        description: 'Deo Tripack - English Lavender,English Rose,Morning Dew (Pack of 3)'
    },
    {
        name: 'Women Blue Flats Sandal',
        category: 'women footware',
        image: 'https://rukminim1.flixcart.com/image/880/1056/jq9swi80/sandal/d/q/x/ft-146-7-skoll-blue-original-imafcbfujx3ru9yk.jpeg?q=50',
        price: 426,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.1,
        tag: '',
        numReviews: 9,
        description: 'High Quality'
    },
    {
        name: 'Women Blue Flats Sandal',
        category: 'women footware',
        image: 'https://rukminim1.flixcart.com/image/880/1056/jq9swi80/sandal/d/q/x/ft-146-7-skoll-blue-original-imafcbfujx3ru9yk.jpeg?q=50',
        price: 426,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.1,
        tag: '',
        numReviews: 9,
        description: 'High Quality'
    },
    {
        name: 'Women Red Flats Sandal',
        category: 'women footware',
        image: 'https://rukminim1.flixcart.com/image/880/1056/kc6jyq80/sandal/r/f/q/half-suede-bow-red-brauch-red-original-imaftd9reeyvex8h.jpeg?q=50',
        price: 399,
        countInStock: 15,
        brand: 'Footware',
        rating: 4,
        tag: '',
        numReviews: 19,
        description: 'High Quality'
    },
    {
        name: 'Women flats Sandal',
        category: 'women footware',
        image: 'https://rukminim1.flixcart.com/image/880/1056/k6b2snk0/sandal/t/v/v/vdfl35-41-belletona-cream-original-imafkyg4hauxg4wk.jpeg?q=50',
        price: 498,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.5,
        tag: '',
        numReviews: 9,
        description: 'High Quality'
    },
    {
        name: 'Women Copper Flats Sandal',
        category: 'women footware',
        image: 'https://rukminim1.flixcart.com/image/880/1056/k7gikcw0/sandal/u/c/n/oval-belt-sandal-copper-42-brauch-copper-original-imafpzuvzrwzndbh.jpeg?q=50',
        price: 399,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.2,
        tag: '',
        numReviews: 9,
        description: 'High Quality'
    },
    {
        name: 'White casual shoes',
        category: 'footware',
        image: 'https://images.meesho.com/images/products/56050658/xnhpu_512.jpg',
        price: 420,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.2,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'White casual shoes',
        category: 'footware',
        image: 'https://images.meesho.com/images/products/56050658/xnhpu_512.jpg',
        price: 420,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.2,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'White casual shoes',
        category: 'footware',
        image: 'https://images.meesho.com/images/products/56050658/xnhpu_512.jpg',
        price: 420,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.4,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'Casual Sneakers and Loafers Shoes',
        category: 'footware',
        image: 'https://images.meesho.com/images/products/56042255/xgpbo_512.jpg',
        price: 208,
        countInStock: 15,
        brand: 'Footware',
        rating: 4.7,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'Running shoes',
        category: 'footware',
        image: 'https://images.meesho.com/images/products/56300995/t2mum_512.jpg',
        price: 1127,
        countInStock: 15,
        brand: 'Footware',
        rating: 3.2,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'Mens Sandal',
        category: 'men footware',
        image: 'https://images.meesho.com/images/products/56292029/y6odn_512.jpg',
        price: 89,
        countInStock: 15,
        brand: 'Footware',
        rating: 3,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'men leather sandal',
        category: 'men footware',
        image: 'https://images.meesho.com/images/products/55899128/xe8go_512.jpg',
        price: 468,
        countInStock: 15,
        brand: 'Footware',
        rating: 3,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'HR1 Sandal',
        category: 'men footware',
        image: 'https://images.meesho.com/images/products/56291949/f2ajl_512.jpg',
        price: 289,
        countInStock: 15,
        brand: 'Footware',
        rating: 3,
        tag: '',
        numReviews: 9,
        description: 'Material : Synthetic, Sole Material : Pvc, Fastening & Back Detail : Lace-Up'
    },
    {
        name: 'BedSheets',
        category: 'home',
        image: 'https://images.meesho.com/images/products/56292111/ol2bu_512.jpg',
        price: 648,
        countInStock: 15,
        brand: 'Rudra Creation',
        rating: 3.8,
        tag: '',
        numReviews: 43,
        description: 'JE Cotton Multi Pattern Double Bed Sheets | Bed Sheet Size-228/228 or Double Bed Size'
    },
    {
        name: 'Single Bedsheets Combo With 4',
        category: 'home',
        image: 'https://images.meesho.com/images/products/32433941/sagr1_512.jpg',
        price: 377,
        countInStock: 10,
        brand: 'Rudra Creation',
        rating: 4.5,
        tag: '',
        numReviews: 43,
        description: 'JE Cotton Multi Pattern Double Bed Sheets | Bed Sheet Size-228/228 or Double Bed Size'
    },
    {
        name: 'COTTON BEDSHEET 90x100',
        category: 'home',
        image: 'https://images.meesho.com/images/products/22019296/e57bf_512.jpg',
        price: 206,
        countInStock: 10,
        brand: 'Rudra Collection',
        rating: 4,
        tag: '',
        numReviews: 43,
        description: 'JE Cotton Multi Pattern Double Bed Sheets | Bed Sheet Size-228/228 or Double Bed Size'
    },
    {
        name: 'bedsheets with pillow cover',
        category: 'home',
        image: 'https://images.meesho.com/images/products/55986685/8dk4r_512.jpg',
        price: 460,
        countInStock: 9,
        brand: 'Rudra Colleaction',
        rating: 3.9,
        tag: '',
        numReviews: 43,
        description: 'JE Cotton Multi Pattern Double Bed Sheets | Bed Sheet Size-228/228 or Double Bed Size'
    },
    {
        name: 'bedsheets with pillow cover',
        category: 'home',
        image: 'https://images.meesho.com/images/products/56134761/1zcaj_512.jpg',
        price: 583,
        countInStock: 15,
        brand: 'Collections',
        rating: 3.8,
        tag: '',
        numReviews: 43,
        description: 'JE Cotton Multi Pattern Double Bed Sheets | Bed Sheet Size-228/228 or Double Bed Size'
    },
    {
        name: 'Classic Stylish Doormats',
        category: 'home',
        image: 'https://images.meesho.com/images/products/21523013/22fd0_512.jpg',
        price: 137,
        countInStock: 15,
        brand: 'Kuber Industries',
        rating: 3.8,
        tag: '',
        numReviews: 43,
        description: 'Free Size (Length Size : 60 cm, Width Size: 40 cm)'
    },
    {
        name: 'Outdoor Welcome MAT',
        category: 'home',
        image: 'https://images.meesho.com/images/products/56237586/yvcj6_512.jpg',
        price: 478,
        countInStock: 5,
        brand: 'Kuber Industries',
        rating: 4,
        tag: '',
        numReviews: 43,
        description: 'Free Size (Length Size : 60 cm, Width Size: 40 cm)'
    },
    {
        name: 'Rubber Door Mat Combo',
        category: 'home',
        image: 'https://images.meesho.com/images/products/54136113/hu0n3_512.jpg',
        price: 230,
        countInStock: 15,
        brand: 'Kuber Industries',
        rating: 4,
        tag: '',
        numReviews: 40,
        description: 'Free Size (Length Size : 60 cm, Width Size: 40 cm)'
    },
    {
        name: 'Stylish Cotton Door Mats',
        category: 'home',
        image: 'https://images.meesho.com/images/products/6617378/c4e85_512.jpg',
        price: 153,
        countInStock: 15,
        brand: 'Kuber Industries',
        rating: 4,
        tag: '',
        numReviews: 43,
        description: 'Free Size (Length Size : 60 cm, Width Size: 40 cm)'
    },
    {
        name: 'Cotton Door Mat Combo',
        category: 'home',
        image: 'https://images.meesho.com/images/products/18096804/aa685_512.jpg',
        price: 131,
        countInStock: 15,
        brand: 'Kuber Industries',
        rating: 3.5,
        tag: '',
        numReviews: 24,
        description: 'Free Size (Length Size : 60 cm, Width Size: 40 cm)'
    },
    {
        name: 'Supremo Window Curtains',
        category: 'home',
        image: 'https://images.meesho.com/images/products/19415488/14904_512.jpg',
        price: 158,
        countInStock: 15,
        brand: 'GANTAVYA COLLECTION',
        rating: 4,
        tag: '',
        numReviews: 24,
        description: 'Material : Polyester, Print or Pattern Type : Floral'
    },
    {
        name: 'Fancy Curtains & Sheers',
        category: 'home',
        image: 'https://images.meesho.com/images/products/22265108/a4303_512.jpg',
        price: 200,
        countInStock: 5,
        brand: 'GANTAVYA COLLECTION',
        rating: 4.3,
        tag: '',
        numReviews: 24,
        description: 'Material : Polyester, Print or Pattern Type : Floral'
    },
    {
        name: 'Versatile Curtains & Sheers',
        category: 'home',
        image: 'https://images.meesho.com/images/products/21086021/2fce3_512.jpg',
        price: 222,
        countInStock: 15,
        brand: 'GANTAVYA COLLECTION',
        rating: 4.6,
        tag: '',
        numReviews: 30,
        description: 'Material : Polyester, Print or Pattern Type : Floral'
    },
    {
        name: 'Polyester Door Curtains',
        category: 'home',
        image: 'https://images.meesho.com/images/products/18086239/9c578_512.jpg',
        price: 482,
        countInStock: 15,
        brand: 'GANTAVYA COLLECTION',
        rating: 4,
        tag: '',
        numReviews: 24,
        description: 'Material : Polyester, Print or Pattern Type : Floral'
    },
    {
        name: 'Supremo Window Curtains',
        category: 'home',
        image: 'https://images.meesho.com/images/products/21532576/a1b8a_512.jpg',
        price: 284,
        countInStock: 15,
        brand: 'GANTAVYA COLLECTION',
        rating: 4.7,
        tag: '',
        numReviews: 24,
        description: 'Material : Polyester, Print or Pattern Type : Floral'
    },
    {
        name: 'Kitchen Food Storage ',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56590580/xzqaj_512.jpg',
        price: 110,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 3.7,
        tag: '',
        numReviews: 20,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'SKI storage container',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56590406/y7iqo_512.jpg',
        price: 280,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 3.9,
        tag: '',
        numReviews: 20,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'Fridge Water Bottle ',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56565399/pvpkb_512.jpg',
        price: 125,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 4,
        tag: '',
        numReviews: 20,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'Big Revolving Spice Rack',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56571057/bgw63_512.jpg',
        price: 273,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 3.5,
        tag: '',
        numReviews: 25,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'Fancy Jars & Containers',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56537772/lph9o_512.jpg',
        price: 143,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 4.2,
        tag: '',
        numReviews: 20,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'Modern Lunch Boxes',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56537903/mtlu5_512.jpg',
        price: 440,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 4.6,
        tag: '',
        numReviews: 50,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'tea and suger pots',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56567273/yrgda_512.jpg',
        price: 192,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 4.2,
        tag: '',
        numReviews: 20,
        description: 'Material : Stainless Steel, Product Breadth : 10 Cm, Product Height : 20 Cm'
    },
    {
        name: 'Wonderful Jars & Containers',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56562051/gwscq_512.jpg',
        price: 192,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 2,
        tag: '',
        numReviews: 20,
        description: 'Material : Glass, Type : Others, Features : Airtight'
    },
    {
        name: 'Stainless Steel Rack',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56520340/yce9r_512.jpg',
        price: 175,
        countInStock: 10,
        brand: 'PUMBHADIYA',
        rating: 4.1,
        tag: '',
        numReviews: 20,
        description: 'Made from superior grade material that helps it improve its rust and corrosion resistance '
    },
    {
        name: 'UCOOK Idli Cooker',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56519517/ucp6k_512.jpg',
        price: 1230,
        countInStock: 10,
        brand: 'Lal Dayal Enterprises',
        rating: 3.9,
        tag: '',
        numReviews: 20,
        description: 'Material : Stainless Steel, Type : With Steamer, Surface Coating : Enamel'
    },
    {
        name: 'Aluminium Fry Pan',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56545143/rbthh_512.jpg',
        price: 193,
        countInStock: 10,
        brand: 'Lal Dayal Enterprises',
        rating: 4.9,
        tag: '',
        numReviews: 20,
        description: 'Material : Aluminium, Type : With Steamer, Surface Coating : Enamel'
    },
    {
        name: 'Combo Kitchen Utensils Set',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56519517/ucp6k_512.jpg',
        price: 594,
        countInStock: 10,
        brand: 'Lal Dayal Enterprises',
        rating: 4,
        tag: '',
        numReviews: 20,
        description: 'Material : Stainless Steel, Type : With Steamer, Surface Coating : Enamel'
    },
    {
        name: 'Hawkins Pressure Cooker',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56520457/qkx8m_512.jpg',
        price: 2100,
        countInStock: 10,
        brand: 'Lal Dayal Enterprises',
        rating: 4.5,
        tag: '',
        numReviews: 20,
        description: 'Material : Stainless Steel, Type : With Steamer, Surface Coating : Enamel'
    },
    {
        name: 'PIZZA PAN',
        category: 'kitchen',
        image: 'https://images.meesho.com/images/products/56511375/1djef_512.jpg',
        price: 385,
        countInStock: 10,
        brand: 'Lal Dayal Enterprises',
        rating: 3.6,
        tag: '',
        numReviews: 20,
        description: ' PIZZA PAN FOR PIZZA LOVERS/10 inch round/ Cutting board/Snacks plate/Pure sheesham'
    },
    {
        name: 'LED Smart Android TV',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/kqidx8w0/television/m/1/v/32ha0a00-oneplus-original-imag4gy8yezxdhen.jpeg?q=70',
        price: 15999,
        countInStock: 10,
        brand: 'Thomsan',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1N Television , 1N Remote Control , 2N AAA Batteries , 2N Desktop stand , 4N Stand Support Screws, 1N Users Manual'
    },
    {
        name: 'LG LED Smart TV',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgkdrjfggbw.jpeg?q=70',
        price: 17500,
        countInStock: 10,
        brand: 'LG',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1N Television , 1N Remote Control , 2N AAA Batteries , 2N Desktop stand , 4N Stand Support Screws, 1N Users Manual'
    },
    {
        name: 'Mi 4X 138.8 cm',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/kq6yefk0/television/e/p/w/l50m5-5ain-mi-original-imag4969ybwxqwza.jpeg?q=70',
        price: 42999,
        countInStock: 10,
        brand: 'MI',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1N Television , 1N Remote Control , 2N AAA Batteries , 2N Desktop stand , 4N Stand Support Screws, 1N Users Manual'
    },
    {
        name: 'BOSCH INVERTER Fully Automatic',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/knknc7k0/washing-machine-new/x/u/g/8-waj2426ain-bosch-original-imag28ftaggavpwm.jpeg?q=70',
        price: 29500,
        countInStock: 10,
        brand: 'BOSCH',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1 Washing Machine, Inlet Hose, User Manual,Energy Rating - 5'
    },
    {
        name: 'Panasoni Fully Automatic',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/knknc7k0/washing-machine-new/x/u/g/8-waj2426ain-bosch-original-imag28ftaggavpwm.jpeg?q=70',
        price: 29500,
        countInStock: 10,
        brand: 'Panasonic',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1 Washing Machine, Inlet Hose, User Manual,Energy Rating - 5'
    },
    {
        name: 'Whirlpool Washing machine',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/kmf7ki80/washing-machine-new/g/b/z/sw-ultra-7-5-sc-grey-10ymw-whirlpool-original-imagfbjgzwy8yzam.jpeg?q=70',
        price: 18890,
        countInStock: 10,
        brand: 'Whirlpool',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1 Washing Machine, Inlet Hose, User Manual,Energy Rating - 5'
    },
    {
        name: 'Haier 4 Star Refrigerator ',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/ke8uv0w0/refrigerator-new/u/j/g/hed-20cfds-4-haier-original-imafuyuth56sxpbd.jpeg?q=70',
        price: 13690,
        countInStock: 10,
        brand: 'Haier',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1 Refrigerator Unit, User Manual, Warranty Card, Ice Tray, Key, Egg Tray'
    },
    {
        name: 'SAMSUNG 253 L Refrigerator',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/kk1h5e80/refrigerator-new/c/d/j/rt28a3453s8-hl-3-2021-samsung-original-imafzhedepq6z5r8.jpeg?q=70',
        price: 23490,
        countInStock: 10,
        brand: 'Samsung',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1 Refrigerator Unit, User Manual, Warranty Card, Ice Tray, Key, Egg Tray'
    },
    {
        name: 'LG 190L Refrigerator ',
        category: 'electronics',
        image: 'https://rukminim1.flixcart.com/image/416/416/k0bbb0w0/refrigerator-new/t/n/z/gl-d201abpy-5-lg-original-imafk4zzgzfdyzzf.jpeg?q=70',
        price: 15690,
        countInStock: 10,
        brand: 'LG',
        rating: 4.9,
        tag: 'diwali dussehra',
        numReviews: 90,
        description: '1 Refrigerator Unit, User Manual, Warranty Card, Ice Tray, Key, Egg Tray'
    },
    {
        name: 'Christmas Home Decoration',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/56610837/yv6q7_512.jpg',
        price: 520,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.5,
        tag: 'christmas diwali',
        numReviews: 70,
        description: 'Type : Decorative Lights, Color : Yellow, Multipack : 1'
    },
    {
        name: 'Festival Home Decoration',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/53448249/bonos_512.jpg',
        price: 89,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.5,
        tag: 'diwali christmas',
        numReviews: 70,
        description: 'Type : Decorative Lights, Color : Yellow, Multipack : 1'
    },
    {
        name: 'Festive Decortaion ',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/49468397/uw0hl_512.jpg',
        price: 300,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.5,
        tag: 'diwali christmas',
        numReviews: 70,
        description: 'Type : Decorative Lights, Color : gold, Multipack : 1'
    },
    {
        name: 'Party Christmas Wedding',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/26182281/f552e_512.jpg',
        price: 130,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.5,
        tag: 'christmas',
        numReviews: 70,
        description: 'Type : Decorative Lights, Color : Yellow, Multipack : 1'
    },
    {
        name: 'Artificial Christmas tree',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/12321773/7c01e_512.jpg',
        price: 800,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.5,
        tag: 'christmas',
        numReviews: 70,
        description: 'Material : Plastic, Pack : Pack of 2, Size : Free Size, Length : 9 cm'
    },
    {
        name: 'Christmas colourful Deers',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/13163883/8c2ad_512.jpg',
        price: 80,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4,
        tag: 'christmas',
        numReviews: 50,
        description: 'Material : Plastic, Pack : Pack of 2, Size : Free Size, Length : 9 cm'
    },
    {
        name: 'Wall and Door hanging',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/13163862/d3778_512.jpg',
        price: 70,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 3.5,
        tag: 'christmas',
        numReviews: 70,
        description: 'Material : Plastic, Pack : Pack of 2, Size : Free Size, Length : 9 cm'
    },
    {
        name: 'Christmas New Year Decoration',
        category: 'festival',
        image: 'https://images.meesho.com/images/products/54026905/j74pj_512.jpg',
        price: 150,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4,
        tag: 'diwali christmas',
        numReviews: 70,
        description: 'Material : Plastic, Pack : Pack of 2, Size : Free Size, Length : 9 cm'
    },
    {
        name: 'Jesus Pendant Chain ',
        category: 'jewellary',
        image: 'https://images.meesho.com/images/products/24582015/51ed3_512.jpg',
        price: 150,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.5,
        tag: 'christmas',
        numReviews: 70,
        description: 'Base Metal : Bras, Plating : Gold Plated'
    },
    {
        name: 'Kids Costume Wear',
        category: 'kidswear',
        image: 'https://rukminim1.flixcart.com/image/880/1056/khcb7gw0/kid-costume-wear/y/k/h/3-santa-claus-costume-for-kids-0-6-months-santa-claus-dress-for-original-imafxcyjn5f8neyd.jpeg?q=50',
        price: 260,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 3.7,
        tag: 'christmas',
        numReviews: 50,
        description: 'FESTDECO SANTA CLAUS Kids Costume Wear'
    },
    {
        name: 'Santa Claus Dress',
        category: 'kidswear',
        image: 'https://rukminim1.flixcart.com/image/880/1056/jb3yp3k0/kid-costume-wear/t/x/r/10-3653-saj-12-original-imafygcudhukc73u.jpeg?q=50',
        price: 540,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 3.7,
        tag: 'christmas',
        numReviews: 50,
        description: 'FESTDECO SANTA CLAUS Kids Costume Wear'
    },
    {
        name: 'Kids Costume Wear',
        category: 'kidswear',
        image: 'https://rukminim1.flixcart.com/image/880/1056/kigbjbk0-0/kid-costume-wear/f/m/p/24-t2kart569-trytokart-60-original-imafy8jbeyzvqtcb.jpeg?q=50',
        price: 200,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.1,
        tag: 'christmas',
        numReviews: 50,
        description: 'FESTDECO SANTA CLAUS Kids Costume Wear'
    },
    {
        name: 'Pencil Decorative Candle',
        category: 'home',
        image: 'https://rukminim1.flixcart.com/image/416/416/j9a8fww0/candle/e/4/g/fruit-pencil-decorative-candle-set-of-6-6-ct-gdcdl-01-clouds-original-imaez32a3zfgye2m.jpeg?q=70',
        price: 290,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 3.3,
        tag: 'diwali christmas',
        numReviews: 50,
        description: 'Decorative Candle, Set of 6, Gel Candles for Home Decoration Party Birthday Wedding Diwali Christmas'
    },
    {
        name: 'Kids Costume Wear',
        category: 'kidswear',
        image: 'https://rukminim1.flixcart.com/image/416/416/kgtqhe80/candle/f/n/g/unscented-fragrance-company-wax-rose-shape-flower-floating-original-imafwz49frfdkc3q.jpeg?q=70',
        price: 167,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4,
        tag: 'diwali christmas',
        numReviews: 20,
        description: 'Decorative Candle, Set of 6, Gel Candles for Home Decoration Party Birthday Wedding Diwali Christmas'
    },
    {
        name: 'Diwali, Christmas Candles',
        category: 'home',
        image: 'https://rukminim1.flixcart.com/image/416/416/ktszgy80/candle/s/e/q/home-decor-na-mosaic-glass-tealight-candle-holders-pack-of-2-original-imag729376cgjr9f.jpeg?q=70',
        price: 295,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.1,
        tag: 'diwali christmas',
        numReviews: 40,
        description: 'Decorative Candle, Set of 6, Gel Candles for Home Decoration Party Birthday Wedding Diwali Christmas'
    },
    {
        name: 'Indoor String Lights',
        category: 'home',
        image: 'https://images.meesho.com/images/products/50290042/b38az_512.jpg',
        price: 95,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.1,
        tag: 'diwali christmas',
        numReviews: 40,
        description: 'Decorative Candle, Set of 6, Gel Candles for Home Decoration Party Birthday Wedding Diwali Christmas'
    },
    {
        name: 'Multi-Color RGB Led String',
        category: 'home',
        image: 'https://images.meesho.com/images/products/10970231/c98d3_512.jpg',
        price: 95,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4,
        tag: 'diwali christmas',
        numReviews: 40,
        description: 'Decorative Candle, Set of 6, Gel Candles for Home Decoration Party Birthday Wedding Diwali Christmas'
    },
    {
        name: ' Diwali Lantern Kandil',
        category: 'home',
        image: 'https://rukminim1.flixcart.com/image/416/416/ktrk13k0/lantern/a/k/j/25-1-butterfly-lantern-for-diwali-dipavali-40-original-imag7fyjfdpbnggv.jpeg?q=70',
        price: 495,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 3,
        tag: 'diwali ',
        numReviews: 40,
        description: 'Made of: Plastic, Color: Multicolor'
    },
    {
        name: 'KREATIONS AKASH KANDIL ',
        category: 'home',
        image: 'https://rukminim1.flixcart.com/image/416/416/ktrk13k0/lantern/a/k/j/25-1-butterfly-lantern-for-diwali-dipavali-40-original-imag7fyjfdpbnggv.jpeg?q=70',
        price: 995,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4,
        tag: 'diwali ',
        numReviews: 40,
        description: 'Made of: Plastic, Color: Multicolor'
    },
    {
        name: 'Kandil light Diwali',
        category: 'home',
        image: 'https://rukminim1.flixcart.com/image/416/416/ktrk13k0/lantern/m/b/r/20-1-1-dipa-50-original-imag7fkwnf8e9bdx.jpeg?q=70',
        price: 495,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 3,
        tag: 'diwali ',
        numReviews: 40,
        description: 'Made of: Plastic, Color: Multicolor'
    },
    {
        name: 'Hanging Lamp Multicolor',
        category: 'home',
        image: 'https://rukminim1.flixcart.com/image/416/416/kq18n0w0/lantern/n/u/x/hlamp3-susajjit-d-cor-original-imag44ua6guhvqrm.jpeg?q=70',
        price: 599,
        countInStock: 10,
        brand: 'SSDYG',
        rating: 4.4,
        tag: 'diwali ',
        numReviews: 40,
        description: 'Made of: Plastic, Color: Multicolor'
    },
]